//! Daemon-side library code: cleanup sweeper, nickname dedup saga, and
//! the on-disk event persister.
//!
//! `link()` is called from the bin to ensure the `inventory` registrations
//! generated by `#[myko_saga]` / `#[myko_command]` survive dead-code
//! elimination. Message delivery itself is handled directly by the
//! `entities::SendMessage` command — there's no saga in the critical path.

pub mod cleanup;
pub mod dedupe_nicknames;
pub mod persister;

pub fn link() {
    dedupe_nicknames::link();
}
