//! Daemon-side library code (currently just sagas).
//!
//! `link()` is called from the bin to ensure the `inventory` registrations
//! generated by `#[myko_saga]` survive dead-code elimination.

pub mod saga;

pub fn link() {
    // The act of referencing the module ensures rustc keeps its inventory
    // registrations.
    saga::link();
}
