//! Daemon-side library code: sagas + the on-disk event persister.
//!
//! `link()` is called from the bin to ensure the `inventory` registrations
//! generated by `#[myko_saga]` survive dead-code elimination.

pub mod cleanup;
pub mod persister;
pub mod rebalance;
pub mod saga;

pub fn link() {
    // The act of referencing the module ensures rustc keeps its inventory
    // registrations.
    saga::link();
}
